version: '3.8'

services:
  postgres:
    image: pg_ais:latest
    container_name: pg_ais_dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_ais_dev
    volumes:
      - .:/app
    working_dir: /app
    command: ["postgres"]
